FROM golang:alpine AS build

COPY . /tmp/otelex

WORKDIR /tmp/otelex/collector
RUN --mount=type=cache,mode=0755,target=/root/.cache/go-build \
    GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -o /otelex .

# Deploy the final (persistent) image
FROM alpine
RUN adduser -S -u 10000 someone
COPY --from=build /otelex /otelex
COPY --from=build /tmp/otelex/config/otelcol-config.yaml collector-config.yaml

ENTRYPOINT ["/otelex"]
CMD ["--config", "collector-config.yaml"]

EXPOSE 4317 4318 12001