dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.125.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.125.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.125.0
